---
title: "figure1"
author: "Cam Reimer"
date: "2/4/2023"
output: html_document
---

```{r}
#Set working directory 

library(ggplot2)
#library(haven)
library(tidyverse)
library(lubridate)
library(dplyr)
library(tidyr)

source("analysis_functions.R")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
```

```{r lm functions}
# functions to do analysis and organize output 
lmfun<-function(data,y,buffer,x, xname){
  # format function call 
  xname = paste(c(paste0(xname,as.character(buffer), "_amax_iqr"),x) , collapse = " + ")
  formula1<-as.formula(paste(y,"~",xname))
  lm.fit<-do.call("lm",list(data=quote(data),formula1))
  return(lm.fit)
}

lmfull<-function(data, y, buffers, x, sig_figs = 3, xname){
  # run models and store as output
  model = vector(mode="list")
  for(i in 1:length(buffers)){
    model[[i]] = lmfun(data = data, y = y, buffer = buffers[i], x = x, xname=xname)
  }
  # format and store summary output
  #results = data.frame(matrix(data = NA, nrow = 1, ncol = length(buffers)))
  results = data.frame(matrix(data = NA, nrow = length(buffers), ncol = 3))
  for(i in 1:length(buffers)){
    main <- as.data.frame(cbind(coef(model[[i]]), confint(model[[i]])))[-1,]
    main <- round(main, sig_figs)
    results[i,] = main[1,]
    #results[,i]<-paste0(main$V1[1]," (", main$`2.5 %`[1], ", ", main$`97.5 %`[1], ")")
    #colnames(results)[i] = paste0("NDVI IQR ", buffers[i], "m")
  }
  #rownames(results) = c("ndvi")
  return(list(model = model, results = results))
}
```

```{r}
x = c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "ct_lths")
buffers = c(50, 100, 250, 500)
xname = "ndvi_"
outcome = "pss_score"
outcome = "b_mdi_score"

#Full
model3_SES1 <- lmfull(data = NSES1, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)
model3_SES2 <- lmfull(data = NSES2, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)
model3_SES3 <- lmfull(data = NSES3, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)

#Urban
model3_SES1_urban <- lmfull(data = NSES1_urban, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)
model3_SES2_urban <- lmfull(data = NSES2_urban, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)
model3_SES3_urban <- lmfull(data = NSES3_urban, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)

#Rural
model3_SES1_rural <- lmfull(data = NSES1_rural, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)
model3_SES2_rural <- lmfull(data = NSES2_rural, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)
model3_SES3_rural <- lmfull(data = NSES3_rural, y = outcome, buffers = buffers, x = x[1:5], sig_figs = 3, xname = xname)

#Bind results into rows
figure1 = rbind(model3_SES1$results, model3_SES2$results, model3_SES3$results, model3_SES1_urban$results, model3_SES2_urban$results, model3_SES3_urban$results, model3_SES1_rural$results, model3_SES2_rural$results, model3_SES3_rural$results )

rm(model3_SES1, model3_SES2, model3_SES3, model3_SES1_urban, model3_SES2_urban, model3_SES3_urban, model3_SES1_rural, model3_SES2_rural, model3_SES3_rural, urban, rural)
```

#group results 
```{r}
#add group categories 
colnames(figure1) = c("Mean", "Lower_CI", "Upper_CI")
figure1$buffer <- rep(c("50m", "100m", "250m", "500m"), 9)
figure1$sample <- c(rep("Full", 12), rep("Urban", 12), rep("Non-Urban", 12))
figure1$quantile <- rep(c(rep("Low NSES", 4), rep("Medium NSES",4), rep("High NSES",4)),3) 

#factorize
figure1$buffer <- factor(figure1$buffer, levels = c("50m", "100m", "250m", "500m"))
figure1$quantile <- factor(figure1$quantile, levels = c("Low NSES", "Medium NSES", "High NSES"))
```

#plot
```{r}
pd = position_dodge(.6)    ### How much to jitter the points on the plot

ggplot(data=figure1, aes(x = buffer, y = Mean, color=quantile))+
  geom_line(aes(linetype = quantile), size=0.5, position = pd)+
  geom_point(aes(colour = factor(quantile)), size=2.5, position = pd)+
  geom_errorbar(aes(ymin=Lower_CI, ymax=Upper_CI, linetype=quantile, col=quantile), size=0.8, position = pd)+
  xlab('NDVI Exposure Buffer Radius')+ ylab("")+
  
  #This line divides the graph in 4 according to time of measurement
  facet_wrap(~sample,strip.position="left",nrow=9,scales = "free_y")+
  geom_hline(yintercept =0, linetype=1)+
  theme(plot.title=element_text(size=16,face="bold"),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_text(face="bold"),
        axis.title=element_text(size=12,face="bold"),
        strip.text.y = element_text(hjust=0,vjust = 1,angle=180,face="bold"))+
  theme_bw()+
  guides(col=guide_legend(ncol=2))+
  theme(legend.position="bottom", legend.key.width=unit(1,"in"),legend.title = element_blank(),legend.text = element_text(colour="black", size = 11))  
  

```
