---
---

```{r}
library(tableone)
library(haven)
library(tidyverse)
library(lubridate)
library(dplyr)
library(labelled)
library(tidyr)
library(mgcv)
library(kableExtra)

#setwd("C:/Users/camer/OneDrive/Documents/SPH/PRESTO")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
```

```{r lm functions}
# functions to do analysis and organize output 
lmfun<-function(data,y,buffer,x, ndvi_measure){
  # format function call 
  xname = paste(c(paste0("ndvi_",as.character(buffer), "_", as.character(ndvi_measure),"_iqr"),x) , collapse = " + ")
  formula1<-as.formula(paste(y,"~",xname))
  lm.fit<-do.call("lm",list(data=quote(data),formula1))
  return(lm.fit)
}

lmfull<-function(data, y, buffers, x, sig_figs = 3, ndvi_measure){
  # run models and store as output
  model = vector(mode="list")
  for(i in 1:length(buffers)){
    model[[i]] = lmfun(data = data, y = y, buffer = buffers[i], x = x, ndvi_measure = ndvi_measure)
  }
  # format and store summary output
  results = data.frame(matrix(data = NA, nrow = 1, ncol = length(buffers)))
  #results = data.frame(matrix(data = NA, nrow = length(buffers), ncol = 3))
  for(i in 1:length(buffers)){
    main <- as.data.frame(cbind(coef(model[[i]]), confint(model[[i]])))[-1,]
    main <- round(main, sig_figs)
   # results[i,] = main[1,]
    results[,i]<-paste0(main$V1[1]," (", main$`2.5 %`[1], ", ", main$`97.5 %`[1], ")")
    colnames(results)[i] = paste0("NDVI IQR ", buffers[i], "m")
    # comment up to last comment
  }
  rownames(results) = c("ndvi")
  return(list(model = model, results = results))
}
```

```{r}
x = c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "ct_HHinc", "ct_lths")
buffers = c(100)
ndvi_measure = "amax"
outcome = "pss_score"
#outcome = "b_mdi_score"

model1_amax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:2], ndvi_measure=ndvi_measure)
model2_amax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:4], ndvi_measure=ndvi_measure)
model3_amax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:6], ndvi_measure=ndvi_measure)
amax <- rbind(model1_amax$results, model2_amax$results, model3_amax$results)

ndvi_measure <- "smax"
model1_smax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:2], ndvi_measure=ndvi_measure)
model2_smax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:4], ndvi_measure=ndvi_measure)
model3_smax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:6], ndvi_measure=ndvi_measure)
smax <- rbind(model1_smax$results, model2_smax$results, model3_smax$results)

ndvi_measure <- "smean"
model1_smean <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:2], ndvi_measure=ndvi_measure)
model2_smean <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:4], ndvi_measure=ndvi_measure)
model3_smean <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:6], ndvi_measure=ndvi_measure)
smean <- rbind(model1_smean$results, model2_smean$results, model3_smean$results)

pss <- cbind(amax, smax, smean)
colnames(pss) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss) <- c("PSS - Model 1", "PSS - Model 2", "PSS - Model 3")
pss
```

```{r}
x = c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "ct_HHinc", "ct_lths")
buffers = c(100)
ndvi_measure = "amax"

outcome = "b_mdi_score"

model1_amax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:2], ndvi_measure=ndvi_measure)
model2_amax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:4], ndvi_measure=ndvi_measure)
model3_amax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:6], ndvi_measure=ndvi_measure)
amax <- rbind(model1_amax$results, model2_amax$results, model3_amax$results)

ndvi_measure <- "smax"
model1_smax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:2], ndvi_measure=ndvi_measure)
model2_smax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:4], ndvi_measure=ndvi_measure)
model3_smax <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:6], ndvi_measure=ndvi_measure)
smax <- rbind(model1_smax$results, model2_smax$results, model3_smax$results)

ndvi_measure <- "smean"
model1_smean <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:2], ndvi_measure=ndvi_measure)
model2_smean <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:4], ndvi_measure=ndvi_measure)
model3_smean <- lmfull(data=data, y=outcome, buffers=buffers, x=x[1:6], ndvi_measure=ndvi_measure)
smean <- rbind(model1_smean$results, model2_smean$results, model3_smean$results)

mdi <- cbind(amax, smax, smean)
colnames(mdi) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi) <- c("MDI - Model 1", "MDI - Model 2", "MDI - Model 3")
mdi
```

```{r}
full <- rbind(pss, mdi)

kbl(full, caption = "100m NDVI Buffer") %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("PSS", 1, 3) %>%
  pack_rows("MDI", 4, 6) 
  

```